name: Dependent PRs

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  schedule:
    - cron: "0 * * * *"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: github.repository_owner == 'axiomhq' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    steps:
      - uses: z0al/dependent-issues@950226e7ca8fc43dc209a7febf67c655af3bdb43 # v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_READ_TOKEN: ${{ secrets.AXIOM_AUTOMATION_TOKEN }}
        with:
          label: dependent
          keywords: depends on, blocked by, needs
